default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :release do
    sh("xcodegen generate --spec ios/project.yml")
    setup_ci if ENV["CI"]
    
    import_certificate(
      certificate_path: "certs/ios_distribution.p12",
      certificate_password: ENV["CERT_PASSWORD"] || "likeart"
    )
    
    install_provisioning_profile(
      path: "certs/likeart_appstore.mobileprovision"
    )
    
    gym(
      project: "ios/LikeArt.xcodeproj",
      scheme: "LikeArt",
      export_method: "app-store",
      output_directory: "build",
      output_name: "LikeArt.ipa",
      include_bitcode: false
    )
    
    upload_to_testflight(
      ipa: "build/LikeArt.ipa",
      api_key: app_store_connect_api_key(
        key_id: ENV["APPSTORE_KEY_ID"],
        issuer_id: ENV["APPSTORE_ISSUER_ID"],
        key_filepath: "certs/AuthKey.p8"
      ),
      skip_waiting_for_build_processing: true
    )
  end
end
