default_platform(:ios)

platform :ios do
  desc "Upload to TestFlight"
  lane :upload do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_filepath: "certs/AuthKey.p8"
    )
    
    upload_to_testflight(
      ipa: "build/LikeArt.ipa",
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
